#!/usr/bin/env bash
set -e

echo "go fmt..."
test -z "$(gofmt -l -w . | tee /dev/stderr)"

if ! [ -x "$(command -v golint)" ]; then
  echo "installing golint..."
  go get -u golang.org/x/lint/golint
fi

echo "go lint..."
test -z "$(golint ./... | tee /dev/stderr)"

echo "go vet..."
test -z "$(go vet -all . 2>&1 | tee /dev/stderr)"

echo "go test..."
go test -race -cover ./...
